# Generated by Django 5.0.1 on 2024-01-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(upload_to='uploads', verbose_name='img'),
        ),
    ]
