# Generated by Django 5.0.1 on 2024-02-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_from', models.IntegerField()),
                ('send_to', models.IntegerField()),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='images/noimage.png', upload_to='uploads/', verbose_name='img'),
        ),
    ]
