# Generated by Django 5.0.1 on 2024-02-04 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_talk_alter_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 19, 37, 22, 601285)),
        ),
    ]
