# Generated by Django 5.0.1 on 2024-03-02 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_talk_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 19, 24, 57, 520684)),
        ),
    ]
